version: "3.9"

services:
  app:
    container_name: desafio-app
    build: ./.docker/
    ports:
      - "${API_PORT:-3000}:3000"
    volumes:
      - .:/app
      - ./.docker/entrypoint.sh:/entrypoint.sh
    environment:
      API_PORT: ${API_PORT:-3000}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_DATABASE: ${DB_DATABASE:-postgres}
    networks:
      - dockernet
    depends_on:
      - db
  db:
    container_name: desafio-db
    image: postgres:13.4-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - dockernet
    restart: unless-stopped

networks:
  dockernet:
    name: dockernet
    driver: bridge
